### ISSUE TITLE
osgeo-grass related paths not properly patched/replaced for 3.10

### ISSUE THREAD

**Issue by AndrewAnnex** [qgis/QGIS-Mac-Packager#25]
this is the underlying cause of #23 I think, it looks like `patch_text_files` might not be patching the grass paths correctly as references to osgeo-grass from the build environment are leaking into the distributed qgis app. I am grepping for all occurrences of osgeo-grass and will post the logs when finished.

**Comment by AndrewAnnex** [comment]
is this issue fixed as of 66ec623523409b3d7b99e155ebf82540dcc5b89b or are the current 3.10 distributions of qgis.org out of date?

**Comment by PeterPetrik** [comment]
I thought I fixed it on nightly builds. If nightly builds work, we can manually trigger (re-) building of LTR and PR. this is probably duplicate of https://github.com/qgis/QGIS/issues/32511

**Comment by AndrewAnnex** [comment]
yeah, I am not using a nightly build, I think this issue is fixed but *might* require the downloads on qgis.org to be updated? If they have been updated then all related issues are probably from users who downloaded 3.10 before the patch. If they have not been updated users will keep posting issues until the next release or they will need to download the nightly distribution. I think I got things working by using the patch you describe in #32511. 

my recurisive gre revealed that grass.sh also has an out-of-date grass_ld_library_path export, but that might not be important

**Comment by grischard** [comment]
The nightly does indeed fix the grass paths. It would be fantastic to have a 3.10-1 release on the website for everyone else.

**Comment by PeterPetrik** [comment]
tomorrow is point release, should be fixed there

**Comment by deitelberg** [comment]
Not sure if this is the right place to post, but I'll go for it. 

Just today I downloaded and installed the 3.10 release and the issue persisted in that release, when using the `r.surf.contour` tool. The error message was this: 
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/clean_temp': '/usr/local/Cellar/osgeo-grass/7.6.1_5/grass76/etc/clean_temp'`

These are the details of my system, with the QGIS version producing the error:
![image](https://user-images.githubusercontent.com/16692712/70096278-f0cdcc80-15e3-11ea-9973-b9aa0a3e65b3.png)

I downloaded and installed the nightly today and the issue was fixed.

**Comment by PeterPetrik** [comment]
@deitelberg the point release 3.10.1 was delayed because of critical blocker bugs with proj integration on windows. best to watch official page for new release
